-- MySQL Script generated by MySQL Workbench
-- Wed Feb 12 11:15:57 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema diagrama-netflix
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema diagrama-netflix
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `diagrama-netflix` DEFAULT CHARACTER SET utf8 ;
USE `diagrama-netflix` ;

-- -----------------------------------------------------
-- Table `diagrama-netflix`.`actors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diagrama-netflix`.`actors` (
  `idactors` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idactors`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diagrama-netflix`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diagrama-netflix`.`users` (
  `idusers` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idusers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diagrama-netflix`.`movies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diagrama-netflix`.`movies` (
  `idmovies` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idmovies`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diagrama-netflix`.`actors_movies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diagrama-netflix`.`actors_movies` (
  `fk_idactors` INT NOT NULL,
  `fk_idmovies` INT NOT NULL,
  `idmovieactors` VARCHAR(45) NOT NULL,
  INDEX `fk_actors_has_movies_movies1_idx` (`fk_idmovies` ASC) VISIBLE,
  INDEX `fk_actors_has_movies_actors_idx` (`fk_idactors` ASC) VISIBLE,
  PRIMARY KEY (`idmovieactors`),
  CONSTRAINT `fk_actors_has_movies_actors`
    FOREIGN KEY (`fk_idactors`)
    REFERENCES `diagrama-netflix`.`actors` (`idactors`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actors_has_movies_movies1`
    FOREIGN KEY (`fk_idmovies`)
    REFERENCES `diagrama-netflix`.`movies` (`idmovies`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diagrama-netflix`.`users_moviesfav`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diagrama-netflix`.`users_moviesfav` (
  `fk_iduser` INT NOT NULL,
  `fk_idmovies` INT NOT NULL,
  `idmoviefav` INT NOT NULL AUTO_INCREMENT,
  INDEX `fk_users_has_movies_movies1_idx` (`fk_idmovies` ASC) VISIBLE,
  INDEX `fk_users_has_movies_users1_idx` (`fk_iduser` ASC) VISIBLE,
  PRIMARY KEY (`idmoviefav`)
 );
 INSERT INTO users_moviesfav (fk_iduser, fk_idmovies)
 VALUES (1,1),(1,2),(2,2);
 SELECT * 
 FROM users_moviesfav;
 ALTER TABLE users_moviesfav add column score int;
 SELECT * 
 FROM users_moviesfav;
 
 -- ---
 -- Table actors_movies
 -- ---
 
 INSERT INTO actors_movies (fk_idactors, fk_idmovies)
 VALUES (1,3),(2,2),(3,1);
 
 

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
